### ISSUE TITLE
Rebel team gains initiative despite having a higher score

### ISSUE THREAD

**Issue by plester1** [videege/flagship#13]
Steps to reproduce:
-Start a RitR campaign
-Submit turn 1 results so that the Rebel team has a higher campaign score
-Observe turn 2 initiative

Expected: The Imperial team should have initiative, as they have a lower campaign score.
Actual: The Rebel team has initiative, even though they have a higher campaign score. See attached screenshot.
![ritr initiative](https://user-images.githubusercontent.com/60946159/74289613-6b9e1c80-4ce4-11ea-861a-037a4f35245c.png)

References:
RitR Campaign Guide, p36 - Strategy Phase, Step 1.1
"Determine Initiative: The team with the the fewest total campaign points has initiative (if both teams are tied, the Rebel team has initiative.)

**Comment by videege** [comment]
Thanks, I'll check this out.

**Comment by videege** [comment]
Fixed.
