### ISSUE TITLE
Token rewards not reflected in refit and expand fleet section

### ISSUE THREAD

**Issue by ande2965** [videege/flagship#20]
I recorded Repair Yard tokens as being selected in the Management Phase, but the Refit & Expand Fleets section says neither team has Repair Yard tokens available. They should be available, and then able to be immediately spent.

![RepairYardsTokenBug](https://user-images.githubusercontent.com/3751084/75104973-f0d2dc80-55d4-11ea-9fc3-88f29ef28a23.png)

**Comment by videege** [comment]
Thanks for the submission!
