### ISSUE TITLE
No ability to add second officer when using Command Staff commander ability

### ISSUE THREAD

**Issue by rythos42** [videege/flagship#51]
To start with, you can't mark your flagship, so maybe should start with that. And then it might be good to add some of the command abilities that let you change up whats on your ship.

**Comment by ryanmessick** [comment]
You can mark your flagship, here’s how:

- Go to your fleet.
- Click the pencil icon to edit the ship you want to be your flagship. 
- Click on commander, then select your fleet name. 
- You will see a red flag next to your ship name.

**Comment by ryanmessick** [comment]
You can add abilities, here’s how:
- Go to view/edit fleet.
- Click Edit Abilities, then add new ability. 
- Dont forget to Click confirm changes to save it.

**Comment by rythos42** [comment]
Aha! Thanks so much!
