### ISSUE TITLE
Standard Deviation (variance) in damage chart not accounting for blank roles

### ISSUE THREAD

**Issue by JimmyBob13** [videege/flagship#70]
When you calculate the variance you're missing the terms for a blank or accuracy.

referencing dieRoll.ts

damageVariance(): number {
        let mean = this.expectedDamage();
        let single = Math.pow(1 - mean, 2);
        let double = Math.pow(2 - mean, 2);
        return (this.pHit * single) +
            (this.pCrit * single) +
            (this.pHitCrit * double) +
            (this.pDoubleHit * double);

you should also have
let miss = Math.pow(0-mean,2);

and the return should also include
(this.pAccuracy*miss)+(this.pBlank*miss)

**Comment by videege** [comment]
Thank you - always glad to have someone checking my math.
