### ISSUE TITLE
Fleet not loading

### ISSUE THREAD

**Issue by ahudson-lush** [videege/flagship#8]
Fleets no longer appear in the Fleet window.  This is the case for new and existing Fleets. Campaigns seem to be fine.

Tried on: 
- mobile (android)
- Win10 
  - Chrome 79.0.39450.117
  - Edge Chromium 79.0.309.65

On Chrome, the console show this error:
![image](https://user-images.githubusercontent.com/19331669/72476288-b38f5980-37a1-11ea-8ec3-eefb03d43c4e.png)

**Comment by videege** [comment]
Sorry to hear you're having trouble.  I think I know the source of this issue and will get to work on a fix.

**Comment by videege** [comment]
@ahudson-lush I pushed an update which I hope addresses this issue.  Can you please confirm if you are still seeing the problem?

**Comment by ahudson-lush** [comment]
Thanks for the response. I just tried it and get the same error in the console.

On a hunch I tried it as a guest and I am able to see fleets, so it could be something with my particular account.
